############# French navigation ##############

# main menu
[[main]]
name = "Accueil"
url = ""
weight = 1

[[main]]
name = "Nos Tarifs"
url = "pricing/"
weight = 2
  
[[main]]
name = "Contact"
url = "contact/"
weight = 3


# footer menu
[[footer]]
name = "Accueil"
url = ""
weight = 1

[[footer]]
name = "Nos Tarifs"
url = "pricing/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3